### PR TITLE
Loading the model using ONNX

### PR DESCRIPTION
**Pull request by lotif**
First, I tried without luck to download the model, it's really complicated to access the filesystem in the context of a browser extension. Then I went to the approach proposed here.

In this PR I am pushing the model and some supporting ONNX files to the repo so it can be bundled into the extension and loaded when the user presses the "Analyze" button.

### CODE REVIEW

**Comment by shainarazavi** [comment]
thanks @lotif can we test it or you want just for us to see code?

**Review by fcogidi — APPROVED** [review]
Can confirm that it runs on firefox - I got the following
```
Page text content has 12216 characters. ONNX session: [object Object]
```
for https://www.cnn.com/2024/10/03/politics/october-surprises-trump-harris-analysis/index.html

Not sure if this is known or not, but I can't close the popup after it runs (unless I reload the tab, close it or go to a new page). 

Does the model get loaded fresh for each new tab?

**Comment by lotif** [comment]
@fcogidi yes, I forgot to add a close button :) easy to do, will work on it on follow up PRs. An inference session is made with the model every time the user clicks on the "Analyze" button.

@shainarazavi to test it, you can clone the repo and follow the instructions in the README. You will need to install [npm](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm) beforehand.

**Comment by fcogidi** [comment]
> @fcogidi yes, I forgot to add a close button :) easy to do, will work on it on follow up PRs. An inference session is made with the model every time the user clicks on the "Analyze" button.

@lotif Can there be a persistent inference session that gets started when the browser extension loads initially and waits to be called? 
Also, do you have an idea yet of how much work it would be to have this running in the background (without the user having to click 'Analyze')?
Not all for this PR, mainly for my own curiosity.

**Comment by lotif** [comment]
@fcogidi yes, we can do the persistent inference session, but I need to figure out how to do that properly first.

I don't think we should run this on the background as the extension code runs for every page that gets loaded in every browser tab. That's a lot of unnecessary computing we will be adding to anyone who has the extension. We can skip the button, though, and run it when the user brings up the extension. In short, I believe it should be an action initiated by the user.

**Comment by fcogidi** [comment]
@lotif Re: running in the background
I get the point of not wasting compute, but what I was thinking w.r.t to running in the background is more like running it once when the page loads (if it is possible, cache the results so that reloading the same page with the same content doesn't trigger an inference call). I was also thinking that we would have a list of websites that the extension would be active on (the whitelist). There are other checks that we probably need to do before inference too. For example, there needs to be at least 20 sentences for the predictions to be useful.

I'm looking at this from a theoretical standpoint of course. I don't know how much work it takes to make it work in practice.

**Comment by lotif** [comment]
@fcogidi I'm more comfortable with running it on load if we have a whitelist of sites. Not hard to do, we can literally just add the sites here:
https://github.com/VectorInstitute/nmb-browser-extension/blob/main/public/manifestv3.json#L14

**Comment by fcogidi** [comment]
@lotif Sounds good.

**Pull request merged**
